const ectoparasitesData = [
  {
    name: "Ixodes scapularis",
    commonName: "Black-legged tick",
    thumbnail: "images/Ixodes-scapularis-1.jpg",
    thumbnailText: "Ixodes scapularis, adult female",
    definitiveHost: "Dogs, various mammals",
    species: ["tick"],
    PPP: "",
    location: "",
    zoonotic: "",
    lifeCycle:
      "Egg → Larva → Nymph → Adult → Engorged female drops off host to lay eggs",
    modeOfInfection: "",
    clinicalSigns: "",
    diagnosis: "Visual identification on skin",
    control: "Tick preventatives",
    additional:
      "Vector for Lyme disease, babesiosis, anaplasmosis/ehrlichiosis",
    lifeCycleImage: "images/Ixodes-scapularis-4.jpg",
    images: [
      "images/Ixodes-scapularis-2.jpg",
      "images/Ixodes-scapularis-3.jpg",
    ],
    imagesDescription: "Ixodes scapularis, adult male",
  },
  {
    name: "Dermacentor variabilis",
    commonName: "American dog tick, Rocky Mountain Wood Tick",
    thumbnail: "images/Dermacentor-variabilis-1.jpg",
    thumbnailText: "Dermacentor variabilis, adult female",
    definitiveHost: "Dogs, various mammals",
    species: ["tick"],
    PPP: "",
    location: "",
    zoonotic: "",
    lifeCycle:
      "Egg → Larva → Nymph → Adult → Female drops off host to lay eggs",
    modeOfInfection: "",
    clinicalSigns: "",
    diagnosis: "Visual identification on skin",
    control: "Tick preventatives",
    additional:
      "Vector for Rocky Mountain spotted fever, tularemia, tick paralysis ",
    lifeCycleImage: "images/Dermacentor-variabilis-5.jpg",
    images: [
      "images/Dermacentor-variabilis-2.jpg",
      "images/Dermacentor-variabilis-3.jpg",
      "images/Dermacentor-variabilis-4.jpg",
    ],
    imagesDescription: "Dermacentor variabilis, adult male",
  },
  {
    name: "Rhipicephalus sanguineus",
    commonName: "Brown dog tick",
    thumbnail: "images/Rhipicephalus-sanguineus-1.jpg",
    thumbnailText: "Rhipicephalus sanguineus, adult female",
    definitiveHost: "Dogs",
    species: ["tick"],
    PPP: "",
    location: "",
    zoonotic: "",
    lifeCycle: "Egg → Larva → Nymph → Adult → Female lays eggs in environment",
    modeOfInfection: "",
    clinicalSigns: "",
    diagnosis: "Visual identification on skin",
    control: "Tick preventatives",
    additional:
      "Most widespread tick in world; adapted to indoor livin. Although this is a 3-host tick, Rhipicephalus sanguineus prefers dogs and can live indoors in dog kennels to complete its life cycle",
    lifeCycleImage: "images/Rhipicephalus-sanguineus-5.jpg",
    images: [
      "images/Rhipicephalus-sanguineus-2.jpg",
      "images/Rhipicephalus-sanguineus-3.jpg",
      "images/Rhipicephalus-sanguineus-4.jpg",
    ],
    imagesDescription: "Rhipicephalus sanguineus, adult male",
  },
  {
    name: "Amblyomma americanum",
    commonName: "Lone star tick",
    thumbnail: "images/Amblyomma-americanum-1.jpg",
    thumbnailText: "Amblyomma americanum, adult tick",
    definitiveHost: "Various mammals, including dogs",
    species: ["tick"],
    PPP: "",
    location: "",
    zoonotic: "",
    lifeCycle: "Egg → Larva → Nymph → Adult → Female lays eggs in environment",
    modeOfInfection: "",
    clinicalSigns: "",
    diagnosis: "Visual identification on skin",
    control: "Tick preventatives",
    additional: "Viable populations have spread",
    lifeCycleImage: "images/Amblyomma-americanum-4.jpg",
    images: [
      "images/Amblyomma-americanum-2.jpg",
      "images/Amblyomma-americanum-3.jpg",
    ],
    imagesDescription: "Amblyomma americanum, nymph stage",
  },
  {
    name: "Trichodectes spp.",
    commonName: "Dog chewing louse",
    thumbnail: "images/Trichodectes-spp-1.jpg",
    thumbnailText: "Trichodectes spp., adult 4x",
    definitiveHost: "Dogs",
    species: ["louse"],
    PPP: "",
    location: "Skin and fur",
    zoonotic: "",
    lifeCycle: "Egg (nits) → Nymph → Adult → Females cement eggs to hair",
    modeOfInfection: ["Direct contact with infested animal", "By fomites"],
    clinicalSigns: "",
    diagnosis: "Visual inspection for nits, hair pluck",
    control: "Topical insecticides, environmental cleaning",
    additional: "Species specific. Pediculosis - infection with lice",
    lifeCycleImage: "",
    images: ["images/Trichodectes-spp-2.jpg"],
    imagesDescription: "Trichodectes spp., adult 10x",
  },
  {
    name: "Linognathus spp.",
    commonName: "Dog sucking louse",
    thumbnail: "images/Linognathus-spp-1.jpg",
    thumbnailText: "Linognathus spp., adult, 4x",
    definitiveHost: "Dogs",
    species: ["louse"],
    PPP: "",
    location: "Skin and fur",
    zoonotic: "",
    lifeCycle: "Egg (nits) → Nymph → Adult → Females cement eggs to hair",
    modeOfInfection: ["Direct contact with infested animal", "By fomites"],
    clinicalSigns: "",
    diagnosis: "Visual inspection for nits, hair pluck",
    control: "Topical insecticides, environmental cleaning",
    additional: "Species specific, blood-sucking parasite",
    lifeCycleImage: "",
    images: [
      "images/Linognathus-spp-2.jpg",
      "images/Linognathus-spp-4.jpg",
      "images/Linognathus-spp-3.jpg",
      "images/Linognathus-spp-5.jpg",
      "images/Linognathus-spp-6.jpg",
    ],
    imagesDescription:
      "Linognathus spp., adult, 4x <br />Linognathus spp., adult <br />Nits on a hair <br />Nits, 4x <br />Nits, 10x <br />",
  },
  {
    name: "Bovicola bovis",
    commonName: "Cattle biting louse",
    thumbnail: "images/Bovicola-bovis-1.jpg",
    thumbnailText: "Bovicola bovis, adult, 4x",
    definitiveHost: "Cattle",
    species: ["louse"],
    PPP: "",
    location: "Skin and fur",
    zoonotic: "",
    lifeCycle: "Egg (nits) → Nymph → Adult → Females cement eggs to hair",
    modeOfInfection: ["Direct contact with infested animal", "By fomites"],
    clinicalSigns: "",
    diagnosis: "Visual inspection for nits, hair pluck",
    control: "Topical insecticides, environmental cleaning",
    additional: "Species specific",
    lifeCycleImage: "",
    images: ["images/Bovicola-bovis-2.jpg"],
    imagesDescription: "Bovicola bovis, adult, 10x",
  },
  {
    name: "Hematopinus spp.",
    commonName: "Cattle sucking louse",
    thumbnail: "images/Hematopinus-spp-1.jpg",
    thumbnailText: "Hematopinus spp., adult, 4x",
    definitiveHost: "Cattle and other livestock",
    species: ["louse"],
    PPP: "",
    location: "Skin and fur",
    zoonotic: "",
    lifeCycle: "Egg (nits) → Nymph → Adult → Females cement eggs to hair",
    modeOfInfection: ["Direct contact with infested animal", "By fomites"],
    clinicalSigns: "",
    diagnosis: "Visual inspection for nits, hair pluck",
    control: "Topical insecticides, environmental cleaning",
    additional: "Species specific, blood-sucking parasite",
    lifeCycleImage: "",
    images: ["images/Hematopinus-spp-2.jpg"],
    imagesDescription: "Hematopinus spp., adult",
  },
  {
    name: "Ctenocephalides spp.",
    commonName: "Flea",
    thumbnail: "images/Ctenocephalides-spp-1.jpg",
    thumbnailText: "Ctenocephalides spp., adult, 4x",
    definitiveHost: "Dogs, cats",
    species: ["flea"],
    PPP: "",
    location: "",
    zoonotic: "",
    lifeCycle: "Egg → Larva → Pupa → Adult → Female lays eggs in environment",
    modeOfInfection: ["Direct contact with infested environment"],
    clinicalSigns:
      "Pruritus, anemia, general dermatitis, flea allergym, dermatitis",
    diagnosis:
      "Visual examination, flea dirt identification, clinical signs, response to treatment",
    control: "",
    additional: "Can transmit Dipylidium caninum",
    lifeCycleImage: "images/Ctenocephalides-spp-5.jpg",
    images: [
      "images/Ctenocephalides-spp-2.jpg",
      "images/Ctenocephalides-spp-3.jpg",
      "images/Ctenocephalides-spp-4.jpg",
    ],
    imagesDescription:
      "Ctenocephalides spp., adult <br /> Ctenocephalides spp., adult, 10x <br /> Ctenocephalides spp., adult, 10x <br />",
  },
  {
    name: "Sarcoptes scabiei",
    commonName: "Scabies",
    thumbnail: "images/Sarcoptes-scabiei-1.jpg",
    thumbnailText: "Sarcoptes scabiei, adult, 40x",
    definitiveHost: "All domestic animals",
    species: ["mite"],
    PPP: "",
    location: "Keratinaceous layer of the host’s epidermis",
    zoonotic: "yes",
    lifeCycle:
      "Egg → Larva (6 legs) → Nymph (2 stages; 8 legs) → Adult (8 legs) → Females burrow into skin and lay up to three eggs per day over a period of 2-3 weeks",
    modeOfInfection: [
      "Direct contact with infested animal or contaminated environment",
      "By fomites",
    ],
    clinicalSigns:
      "Intense pruritus, lesions start on the tips of ears, elbows and hocks then move to rest of bod",
    diagnosis: "Skin scraping, responst to treatment, skin biopsy",
    control: "",
    additional: "Highly contagious. Round body, short leggs, long pedicles",
    lifeCycleImage: "images/Sarcoptes-scabiei-3.jpg",
    images: ["images/Sarcoptes-scabiei-2.jpg"],
    imagesDescription: "Sarcoptes scabiei, adult, 10x",
  },
  {
    name: "Cheyletiella spp.",
    commonName: "Walking dandruff mite",
    thumbnail: "images/Cheyletiella-spp-1.jpg",
    thumbnailText: "Cheyletiella spp., adult, 40x",
    definitiveHost: "Birds, small mammal",
    species: ["mite"],
    PPP: "",
    location: "On fur",
    zoonotic: "yes",
    lifeCycle: "Egg → Larva → Nymph → Adult → Entirely on host",
    modeOfInfection: [
      "Direct contact with infested animal or contaminated environment",
      "By fomites",
    ],
    clinicalSigns:
      "Excessive scaling, especially over back, mild to severe pruritus, crusts",
    diagnosis: "Visual identification, skin scraping, acetate tape prep",
    control: "",
    additional:
      "Highly contagious. Hooked mouthparts for piercing the skin; comb at end of legs",
    lifeCycleImage: "",
    images: ["images/Cheyletiella-spp-2.jpg", "images/Cheyletiella-spp-3.jpg"],
    imagesDescription: "Cheyletiella spp., adult, 10x",
  },
  {
    name: "Demodex spp.",
    commonName: "Demodectic mange",
    thumbnail: "images/Demodex-spp-1.jpg",
    thumbnailText: "Demodex spp., adult, 40x",
    definitiveHost: "Dogs, cats",
    species: ["mite"],
    PPP: "",
    location: "Hair follicles, sebaceous gland ducts",
    zoonotic: "",
    lifeCycle: "Egg → Larva → Nymph → Adult",
    modeOfInfection: ["Direct contact with mother during nursing"],
    clinicalSigns:
      "Localized: Small area(s) of alopecia (often on head). Generalized: Involves entire body, secondary infection may cause pruritu",
    diagnosis: "Deep skin scraping, hair pluck, skin biopsy",
    control: "",
    additional:
      "Considered normal mammalian fauna. Demodicosis - overpopulation of Demodex spp.",
    lifeCycleImage: "images/Demodex-spp-3.jpg",
    images: ["images/Demodex-spp-2.jpg"],
    imagesDescription: "Demodex spp., adult, 10x",
  },
  {
    name: "Otodectes cynotis",
    commonName: "Ear mite",
    thumbnail: "images/Otodectes-cynotis-1.jpg",
    thumbnailText: "Otodectes cynotis, adult, 10x",
    definitiveHost: "Dogs, cats",
    species: ["mite"],
    PPP: "",
    location: "Surface of skin, skin in ear canals",
    zoonotic: "",
    lifeCycle: "Egg → Larva → Nymph → Adult",
    modeOfInfection: "",
    clinicalSigns: "Dark ear discharge (coffee grounds), pruritus",
    diagnosis:
      "Microscope examination of debris from ears with mineral oil on 10x",
    control: "",
    additional:
      "Round body, long legs, short pedicles with wine glass-like suckers",
    lifeCycleImage: "",
    images: [
      "images/Otodectes-cynotis-2.jpg",
      "images/Otodectes-cynotis-3.jpg",
    ],
    imagesDescription:
      "Otodectes cynotis, adult, 10x <br /> Otodectes cynotis, adult, 40x",
  },
  {
    name: "Cuterebra spp.",
    commonName: "Botfly",
    thumbnail: "images/Cuterebra-spp-1.jpg",
    thumbnailText: "Cuterebra spp., adult",
    definitiveHost: "Rodents, occasionally dogs and cats (aberrant host)",
    species: ["fly"],
    PPP: "",
    location: "Subcutaneous tissues",
    zoonotic: "",
    lifeCycle:
      "Egg → Larva → Enter body through natural openings or skin wounds → Migrate to tissues → Mature → Fall out of body → Pupate in soil, and fly away ",
    modeOfInfection: ["Larvae enter host’s skin and form a breathing hole"],
    clinicalSigns:
      "Swelling, small breathing hole, potential secondary bacterial infection infection",
    diagnosis: "Visual examination of breathing holes with larva",
    control:
      "Removal of larva using forceps through breathing hole, secondary bacterial infection treatment",
    additional: "",
    lifeCycleImage: "images/Cuterebra-spp-3.jpg",
    images: ["images/Cuterebra-spp-2.jpg"],
    imagesDescription: "Cuterebra spp., adult",
  },
  {
    name: "Melophagus ovinus",
    commonName: "Sheep ked",
    thumbnail: "images/Melophagus-ovinus-1.jpg",
    thumbnailText: "Melophagus ovinus, adult, 4x",
    definitiveHost: "Sheep, goat",
    species: ["fly"],
    PPP: "",
    location: "Skin and wool",
    zoonotic: "",
    lifeCycle: "Egg → Larva → Pupates on host → Adult",
    modeOfInfection: "",
    clinicalSigns: "Intense pruritus, anemia",
    diagnosis: "Visual inspection of wool and skin",
    control: "",
    additional:
      "Wingless fly. Feed on blood. Ked feces stain wool = economic loss",
    lifeCycleImage: "",
    images: [
      "images/Melophagus-ovinus-2.jpg",
      "images/Melophagus-ovinus-3.jpg",
      "images/Melophagus-ovinus-4.jpg",
    ],
    imagesDescription:
      "Melophagus ovinus, adult, 4x <br /> Melophagus ovinus, adult",
  },
  {
    name: "Gastrophilus spp.",
    commonName: "Horse botfly",
    thumbnail: "images/Gastrophilus-spp-1.jpg",
    thumbnailText: "Gastrophilus spp., adult",
    definitiveHost: "Horses",
    species: ["fly"],
    PPP: "1 year",
    location: "Stomach, first part of small intestine",
    zoonotic: "",
    lifeCycle: "Egg → Larva → Pupates in soil → Adult fly lays eggs on fur",
    modeOfInfection: [
      "Larvae migrate to stomach after being licked and ingested",
    ],
    clinicalSigns: "Rarely pathogenic, gastritis, enteritis, stomatitis",
    diagnosis: "Eggs on hair, larvae (bots) in feces",
    control: "",
    additional: "Larvae attach to stomach by hooks",
    lifeCycleImage: "images/Gastrophilus-spp-3.jpg",
    images: ["images/Gastrophilus-spp-2.jpg"],
    imagesDescription: "Gastrophilus spp., adult",
  },
];
