const endoparasitesData = [
  {
    name: "Toxocara spp.",
    commonName: "Roundworm",
    thumbnail: "images/Toxocara-1.jpg",
    thumbnailText:
      "Toxocara spp., ova, dog, 40x, photo taken from Sabrina’s slide",
    definitiveHost: "Dog, cat",
    species: ["dog", "cat"],
    PPP: "≈6 weeks (dog) / ≈7 weeks (cat)",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Ingestion → migrate through organs → lungs → trachea → coughed up → swallowed → small intestine → mature → eggs shed in feces",
    modeOfInfection: [
      "Directly by ingesting infective egg",
      "Indirectly by ingesting a paratenic host (e.g. rodent)",
      "Transmammary from bitch",
      "Transplacental from bitch (only dogs)",
    ],
    clinicalSigns:
      "Pot-belly, dry lack-luster hair, underweight, vomiting, diarrhea, coughing",
    diagnosis: "Fecal flotation",
    control:
      "Remove feces from environment, treat puppies/kittens & bitch/queen",
    additional:
      "Most common endoparasite of dogs & cats, especially puppies/kittens ",
    lifeCycleImage: "images/Toxocara-LC.jpg",
    images: ["images/Toxocara-2.jpg"],
    imagesDescription: "Toxocara spp., adult",
  },
  {
    name: "Parascaris equorum",
    commonName: "Roundworm",
    thumbnail: "images/Parascaris-equorum-1.jpg",
    thumbnailText: "Parascaris equorum, ova, horse, 40x",
    definitiveHost: "Equine",
    species: ["equine"],
    PPP: "12 weeks",
    location: "Small intestine",
    zoonotic: "no",
    lifeCycle:
      "Ingest ova → migrate liver/lungs → coughed up, swallowed → adults in small intestine",
    modeOfInfection: ["Directly infective ova on pastures and stalls"],
    clinicalSigns:
      "Pot-belly, unthrifty appearance, intermittent colic, constipation or diarrhea, coughing. Adult horses usually have no clinical signs and very few worms",
    diagnosis: "Fecal flotation",
    control: "Antiparasitic treatment (resistance is becoming an issue)",
    additional: "",
    lifeCycleImage: "images/Parascaris-equorum-3.jpg",
    images: ["images/Parascaris-equorum-2.jpg"],
    imagesDescription: "Parascaris equorum, adult",
  },
  {
    name: "Trichuris vulpis",
    commonName: "Whipworm",
    thumbnail: "images/Trichuris-spp-1.jpg",
    thumbnailText: "Trichuris vulpis, ova, 40x",
    definitiveHost: "Dog, fox, coyote",
    species: ["dog"],
    PPP: "≈3 months",
    location: "Large intestine, cecum",
    zoonotic: "yes; rare",
    lifeCycle:
      "Ingestion → mature in large intestine → eggs shed in feces (9-21 days for egg to become infective)",
    modeOfInfection: ["Directly through ingestion of infective egg"],
    clinicalSigns: "Severe watery diarrhea, anemia, hematochezia",
    diagnosis: "Fecal flotation",
    control: "",
    additional: "Ova remain viable in environment for years; difficult to kill",
    lifeCycleImage: "images/Trichuris-spp-4.jpg",
    images: ["images/Trichuris-spp-2.jpg", "images/Trichuris-spp-3.jpg"],
    imagesDescription: "Trichuris vulpis, adult",
  },
  {
    name: "Ancylostoma spp.",
    commonName: "Hookworm",
    thumbnail: "images/Ancylostoma-spp-1.jpg",
    thumbnailText: "Ancylostoma caninum, ova, dog, 40x",
    definitiveHost: "Dog, cat",
    species: ["dog", "cat"],
    PPP: "≈2 weeks (dog) / ≈3 weeks (cat)",
    location: "Small intestine; ingest blood",
    zoonotic: "yes (skin penetration)",
    lifeCycle:
      "Ingestion → larvae penetrate skin → migrate through tissues → lungs → trachea → coughed up → swallowed → small intestine → mature → eggs shed in feces",
    modeOfInfection: [
      "Directly by ingesting infective larvae",
      "Indirectly by ingesting a paratenic host (e.g. vertebrate, cockroach)",
      "Transmammary from bitch (only dogs)",
      "Transplacental from bitch (only dogs)",
      "Through skin penetration",
    ],
    clinicalSigns:
      "Anemia, diarrhea, weakness, melena, dermatitis, respiratory disease",
    diagnosis:
      "Fecal flotation (fresh feces, skin biopsy), fecal antigen testing",
    control: "Remove feces from environment, treat dogs and bitches",
    additional: "Killed by freezing temperatures",
    lifeCycleImage: "images/Ancylostoma-spp-5.jpg",
    images: [
      "images/Ancylostoma-spp-2.jpg",
      "images/Ancylostoma-spp-3.jpg",
      "images/Ancylostoma-spp-4.jpg",
    ],
    imagesDescription:
      "Ancylostoma caninum, larvated ova, dog, 40x <br/> Ancylostoma spp., adult, 4x",
  },
  {
    name: "Strongyloides stercoralis",
    commonName: "Threadworm",
    thumbnail: "images/Strongyloides-spp-1.jpg",
    thumbnailText: "Strongyloides stercoralis, adult, 40x",
    definitiveHost: "Dog, cat",
    species: ["dog", "cat"],
    PPP: "8-14 days",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Skin penetration → migrate through tissues → lungs → trachea → coughed up → swallowed → small intestine → ova hatch → move to feces",
    modeOfInfection: [
      "Directly through skin penetration",
      "Directly through ingestion of infective larvae",
    ],
    clinicalSigns: "Severe diarrhea, respiratory signs",
    diagnosis: "Baermann technique, skin scraping",
    control: "",
    additional: "",
    lifeCycleImage: "images/Strongyloides-spp-2.jpg",
    images: [],
    imagesDescription: "",
  },
  {
    name: "Strongyles",
    commonName: "Bloodworms",
    thumbnail: "images/Strongyles-1.jpg",
    thumbnailText: "Strongyles, ova, horse, 10x",
    definitiveHost: "Equine",
    species: ["equine"],
    PPP: "6-11 months",
    location: "Large intestine, cecum",
    zoonotic: "no",
    lifeCycle:
      "Ingestion of infective larvae → larvae penetrate the intestinal wall → migrate (liver, lungs, mesenteric arteries) → large intestine",
    modeOfInfection: ["Direct ingestion of infective larvae"],
    clinicalSigns:
      "Colic, weight loss or poor weight gain, hind-limb lameness, aneurysms and infarcts (larval migration), anemia, death",
    diagnosis: "Fecal flotation",
    control: "Pasture management",
    additional: "",
    lifeCycleImage: "images/Strongyles-4.jpg",
    images: ["images/Strongyles-2.jpg", "images/Strongyles-3.jpg"],
    imagesDescription: "Strongyles, ova, horse, 40x <br />Strongyles, adult",
  },
  {
    name: "Dioctophyme renale",
    commonName: "Giant kidney worm",
    thumbnail: "images/Dioctophyma-renale-1.jpg",
    thumbnailText: "Dioctophyme renale, adult",
    definitiveHost: "Dog, cat",
    species: ["dog", "cat"],
    PPP: "5 months",
    location: "Kidney (right); peritoneal cavity",
    zoonotic: "yes",
    lifeCycle:
      "Ingestion → larvae penetrate stomach → migrate to abdominal cavity → right kidney",
    modeOfInfection: [
      "Directly by ingesting intermediate host (earthworm)",
      "Indirectly by ingesting paratenic host (frog, fish, crayfish)",
    ],
    clinicalSigns: "None to hematuria, renal dysfunction",
    diagnosis: "Urine sedimentation",
    control: "",
    additional: "Adults up to 60 cm long",
    lifeCycleImage: "images/Dioctophyma-renale-2.jpg",
    images: [],
    imagesDescription: "",
  },
  {
    name: "Taenia spp.",
    commonName: "Rodent Tapeworm",
    thumbnail: "images/Taenia-spp-1.jpg",
    thumbnailText: "Taenia spp., ova, 40x",
    definitiveHost: "Dog, cat",
    species: ["dog", "cat"],
    PPP: "2 months (dog) /  1.5 months (cat)",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Ingestion → larvae develop in intermediate host → dog ingests host → adult in small intestine",
    modeOfInfection: ["Ingestion of infected intermediate host (rabbit/hare)"],
    clinicalSigns: "Usually none",
    diagnosis:
      "Finding proglottids on feces or on pet (look like rice grains when dry), fecal flotation",
    control: "",
    additional: "Up to 200 cm long",
    lifeCycleImage: "images/Taenia-spp-3.jpg",
    images: ["images/Taenia-spp-2.jpg"],
    imagesDescription: "Taenia pisiformis, adult",
  },
  {
    name: "Dipylidium caninum",
    commonName: "Flea Tapeworm",
    thumbnail: "images/Dipilidium-caninum-1.jpg",
    thumbnailText: "Dipylidium caninum, ova, 40x",
    definitiveHost: "Dogs & cats",
    species: ["dog", "cat"],
    PPP: "2-4 weeks",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Flea larva ingests eggs → cysticercoid develops in flea → dog/cat ingests flea → protoscolex attaches in small intestine → tapeworm matures and releases proglottids",
    modeOfInfection: [
      "Ingestion of infected intermediate host (flea or louse)",
    ],
    clinicalSigns:
      "None, scooting, proglottids on perineal region, in stool or bedding",
    diagnosis:
      "Proglottids on pet, in feces, or in environment (grains of rice when dry), fecal flotation",
    control: "",
    additional:
      "Most common tapeworm of dogs and cats. Important to treat the fleas and/or lice",
    lifeCycleImage: "images/Dipilidium-caninum-5.jpg",
    images: [
      "images/Dipilidium-caninum-2.jpg",
      "images/Dipilidium-caninum-3.jpg",
      "images/Dipilidium-caninum-4.jpg",
    ],
    imagesDescription:
      "Dipylidium caninum, ova - egg packets, no shell, 40x <br />Dipylidium caninum, ova - individual packet, 40x, <br />Dipylidium caninum, adult",
  },
  {
    name: "Anoplocephala spp. & Paranoplocephala spp.",
    commonName: "Tapeworm",
    thumbnail: "images/Anoplocephala-spp-1.jpg",
    thumbnailText: "Anoplocephala spp./Paranoplocephala spp., adult",
    definitiveHost: "Equine",
    species: ["equine"],
    PPP: "2 months",
    location: "Small intestine, large intestine, cecum",
    zoonotic: "no",
    lifeCycle:
      "Segments in stool → eggs released → mites ingest eggs → cysticercoid forms in mite → horse eats mite → cysticercoid matures in gut",
    modeOfInfection: ["Ingestion of infected forage mites"],
    clinicalSigns:
      "None (in light infections), ulceration, inflammation of gut, intestinal obstruction, colic",
    diagnosis: "Proglottid segments in feces, fecal flotation",
    control: "",
    additional: "",
    lifeCycleImage: "images/Anoplocephala-spp-2.jpg",
    images: [],
    imagesDescription: "",
  },
  {
    name: "Echinococcus granulosus",
    commonName: "Hydatid tapeworm",
    thumbnail: "images/Echinococcus-granulosus-1.jpg",
    thumbnailText: "Echinococcus granulosus, adult, 4x",
    definitiveHost: "Dogs and other canids",
    species: ["dog"],
    PPP: "≈2 months",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Animal ingests egg → oncosphere to tissue → dog ingests tissue → cysts develop into adult → proglottid ruptures, eggs passed → eggs survive in environment for up to 1 year",
    modeOfInfection: ["Ingestion of eggs in environment"],
    clinicalSigns: "None",
    diagnosis: "Eggs in fecal flotation (same as Taenia spp.), PCR, ELISA",
    control: "Cook meat, prevent fecal-oral transmission in humans",
    additional:
      "Any mammal can be an intermediate host. Adult consists of 3 proglottids",
    lifeCycleImage: "images/Echinococcus-granulosus-2.jpg",
    images: [],
    imagesDescription: "",
  },
  {
    name: "Echinococcus multilocularis",
    commonName: "Hydatid tapeworm",
    thumbnail: "images/Echinococcus-multilocularis-1.jpg",
    thumbnailText: "Echinococcus multilocularis, adult, 4x",
    definitiveHost: "Dogs and other canids",
    species: ["dog"],
    PPP: "≈2 months",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Animal ingests egg → oncosphere to tissue → dog ingests tissue → cysts develop into adult → proglottid ruptures, eggs passed → eggs survive in environment for up to 1 year",
    modeOfInfection: ["Ingestion of eggs in environment"],
    clinicalSigns: "None",
    diagnosis: "Eggs in fecal flotation (same as Taenia spp.), PCR, ELISA",
    control: "Cook meat, prevent fecal-oral transmission in humans",
    additional:
      "Any mammal can be an intermediate host. Adult consists of 3 proglottids",
    lifeCycleImage: "images/Echinococcus-multilocularis-4.jpg",
    images: [
      "images/Echinococcus-multilocularis-2.jpg",
      "images/Echinococcus-multilocularis-3.jpg",
    ],
    imagesDescription:
      "Echinococcus multilocularis, adult, suckers, 10x <br /> Echinococcus multilocularis, adult, eggs, 10x",
  },
  {
    name: "Spirometra spp.",
    commonName: "Zipper tapeworm",
    thumbnail: "images/Spirometra-spp-1.jpg",
    thumbnailText: "Spirometra spp., adult",
    definitiveHost: "Dogs, cats, wild carnivores",
    species: ["dog", "cat"],
    PPP: "10 days",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Eggs in feces → hatch in water, releasing larva → copepod ingests larva → fish eats copepod, larva develop further → definitive host ingests fish → larvae mature into adult tapeworm in small intestine",
    modeOfInfection: [
      "Ingestion of infected fish or amphibian",
      "Directly through ingestion of copepods containing infective stages",
    ],
    clinicalSigns:
      "Vomiting, diarrhea, weight loss; larvae may migrate to subcutaneous regions, eyes, or CNS",
    diagnosis: "Fecal centrifuge flotation",
    control: "",
    additional:
      "1st intermediate host - copepod; 2nd intermediate host –reptiles, mammals, birds",
    lifeCycleImage: "images/Spirometra-spp-2.jpg",
    images: [],
    imagesDescription: "",
  },
  {
    name: "Diphyllobothrium latum",
    commonName: "Broad fish tapeworm",
    thumbnail: "images/Diphyllobothrium-spp-1.jpg",
    thumbnailText: "Diphyllobothrium latum, ova, 40x",
    definitiveHost: "Dogs, cats, humans, other mammals",
    species: ["dog", "cat"],
    PPP: "4-6 weeks",
    location: "Small intestine",
    zoonotic: "yes",
    lifeCycle:
      "Eggs in feces → hatch in water, releasing larva → copepod ingests larva → fish ingests copepod, larva develop further → definitive host ingests fish, developing into adult in small intestine",
    modeOfInfection: ["Ingestion of infected fish"],
    clinicalSigns: "Usually none",
    diagnosis: "Fecal flotation, segment crush",
    control: "",
    additional:
      "Adults 2-12 meters; 1st intermediate host - aquatic crustacean like a copepo; 2nd intermediate host – fish",
    lifeCycleImage: "images/Diphyllobothrium-spp-3.jpg",
    images: ["images/Diphyllobothrium-spp-2.jpg"],
    imagesDescription: "Diphyllobothrium latum, adult",
  },
];
